CREATE TABLE IF NOT EXISTS `sites` (
  `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `domain` varchar(255) NOT NULL,
  `base_url` varchar(255) NOT NULL,
  `website_name` varchar(255) NOT NULL,
  `logo_path` varchar(255) DEFAULT NULL,
  `seo_title` varchar(255) DEFAULT NULL,
  `seo_description` text,
  `geo_text` text,
  `contact_mail` varchar(255) DEFAULT NULL,
  `contact_mail_cnt_form` varchar(255) DEFAULT NULL,
  `contact_number` varchar(100) DEFAULT NULL,
  `contact_number_html` varchar(100) DEFAULT NULL,
  `mobile_contact_number` varchar(100) DEFAULT NULL,
  `mobile_contact_number_html` varchar(100) DEFAULT NULL,
  `address` text,
  `correspondence_address` text,
  `map_link` varchar(255) DEFAULT NULL,
  `facebook_link` varchar(255) DEFAULT NULL,
  `youtube_link` varchar(255) DEFAULT NULL,
  `twitter_link` varchar(255) DEFAULT NULL,
  `snapchat_link` varchar(255) DEFAULT NULL,
  `instagram_link` varchar(255) DEFAULT NULL,
  `pinterest_link` varchar(255) DEFAULT NULL,
  `google_link` varchar(255) DEFAULT NULL,
  `linkedin_link` varchar(255) DEFAULT NULL,
  `is_default` tinyint(1) NOT NULL DEFAULT '0',
  `status` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_sites_domain` (`domain`),
  KEY `idx_sites_status` (`status`),
  KEY `idx_sites_default` (`is_default`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `site_page_overrides` (
  `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `site_id` int(10) UNSIGNED NOT NULL,
  `page_id` int(10) UNSIGNED NOT NULL,
  `menu_title` varchar(255) DEFAULT NULL,
  `page_title` varchar(255) DEFAULT NULL,
  `h1_title` varchar(255) DEFAULT NULL,
  `content` mediumtext,
  `meta_title` varchar(255) DEFAULT NULL,
  `meta_description` text,
  `geo_text` text,
  `status` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_site_page_overrides_site_page` (`site_id`, `page_id`),
  KEY `idx_site_page_overrides_page` (`page_id`),
  CONSTRAINT `fk_site_page_overrides_site` FOREIGN KEY (`site_id`) REFERENCES `sites` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT IGNORE INTO `sites` (
  `domain`,
  `base_url`,
  `website_name`,
  `logo_path`,
  `seo_title`,
  `seo_description`,
  `geo_text`,
  `is_default`,
  `status`
) VALUES
(
  'propertiesarounditaly.com',
  'https://propertiesarounditaly.com/',
  'Properties Around Italy',
  '/assets/img/logo_reverse.png',
  'Properties Around Italy',
  'Italian property specialists with shared listings and brand-specific content.',
  'Italy',
  1,
  1
),
(
  'propertiesforsaleinabruzzo.com',
  'https://propertiesforsaleinabruzzo.com/',
  'Properties for Sale in Abruzzo',
  '/assets/img/logo_reverse.png',
  'Properties for Sale in Abruzzo',
  'Abruzzo property listings with tailored local content and SEO.',
  'Abruzzo, Italy',
  0,
  1
);
